proyecto0Make: main_p.c car.c car.h dijkstra.c dijsktra.h configReader.h readWeightMatrix.h readWeightMatrix.c usableSpaces.c usableSpaces.h readGUIMapping.h readGUIMapping.c
	gcc -o proyecto1 main_p.c car.c readWeightMatrix.c readGUIMapping.c dijkstra.c usableSpaces.c -lm -lpthread -lSDL -I.
